# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../original/add_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_dlg(object):
    def setupUi(self, add_dlg):
        add_dlg.setObjectName("add_dlg")
        add_dlg.setWindowModality(QtCore.Qt.WindowModal)
        add_dlg.resize(295, 118)
        add_dlg.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(add_dlg)
        self.gridLayout.setObjectName("gridLayout")
        self.cancel = QtWidgets.QPushButton(add_dlg)
        self.cancel.setObjectName("cancel")
        self.gridLayout.addWidget(self.cancel, 3, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(add_dlg)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 1, 0, 1, 3)
        self.ok = QtWidgets.QPushButton(add_dlg)
        self.ok.setObjectName("ok")
        self.gridLayout.addWidget(self.ok, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(add_dlg)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        self.widget = QtWidgets.QWidget(add_dlg)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.customEdit = QtWidgets.QLineEdit(self.widget)
        self.customEdit.setObjectName("customEdit")
        self.gridLayout_2.addWidget(self.customEdit, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 2, 0, 1, 3)

        self.retranslateUi(add_dlg)
        QtCore.QMetaObject.connectSlotsByName(add_dlg)
        add_dlg.setTabOrder(self.comboBox, self.ok)
        add_dlg.setTabOrder(self.ok, self.cancel)

    def retranslateUi(self, add_dlg):
        _translate = QtCore.QCoreApplication.translate
        add_dlg.setWindowTitle(_translate("add_dlg", "Add extra"))
        self.cancel.setText(_translate("add_dlg", "Cancel"))
        self.ok.setText(_translate("add_dlg", "Ok"))
        self.label.setText(_translate("add_dlg", "Available extras"))
        self.customEdit.setPlaceholderText(_translate("add_dlg", "1Mg26:1S32 or 133Cs"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    add_dlg = QtWidgets.QDialog()
    ui = Ui_add_dlg()
    ui.setupUi(add_dlg)
    add_dlg.show()
    sys.exit(app.exec_())
