
FILE_EXTENSION = 'MPANT (*.mpa);; CSV (*.csv);; JYFL (*.txt) '
ISOLTRAP_BUNCHER_TO_CAVITY = 3/4
JYFL_BUNCHER_TO_CAVITY = 124/173
DIST_BUNCHER_TO_CAVITY = 0.71
DIST_CAVITY_TO_MCP = 0.26
OFFSET = 0.04
